image: Visual Studio 2019

environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

install:
  - dotnet tool install -g codecov.tool

configuration:
  - Release

build_script:
  - cmd: dotnet pack

test_script:
  - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=./Coverage.xml

after_test:
  - codecov -f test/ReportPortal.Shared.Tests/Coverage.*.xml
  - dotnet run -c Release --project test/ReportPortal.Shared.Benchmark

artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.html'