image: Visual Studio 2017

install:
  - gitversion /l console /output buildserver
  - dotnet tool install -g codecov.tool

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
  - cmd: dotnet build

test_script:
  - cmd: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=./Coverage.xml

after_test:
  - dotnet pack
  - codecov -f .\test\ReportPortal.Shared.Tests\Coverage.xml
  - dotnet run -c Release --project test\ReportPortal.Shared.Benchmark

artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.html'